trigger:
  branches:
    include:
    - main
  paths:
    include:
    - /src/APIGateway
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: main
jobs:
- job: Job_1
  displayName: Agent job 1
  timeoutInMinutes: 7
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: src/APIGateway/Aggregator/Aggregator.csproj
  - task: DotNetCoreCLI@2
    displayName: Build Aggregator
    inputs:
      projects: src/APIGateway/Aggregator/Aggregator.csproj
      arguments: --configuration $(BuildConfiguration)
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
...
