variables:
  - name: BuildParameters.ArtifactName
    value: drop
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - /src/Services/Edu
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
    - repository: self
      type: git
      ref: main
jobs:
  - job: Job_1
    displayName: Agent job 1
    pool:
      vmImage: windows-2019
    steps:
      - checkout: self
        lfs: true
      - task: NuGetToolInstaller@1
        displayName: Use NuGet 6.0.0
        inputs:
          versionSpec: 6.0.0
          checkLatest: true
      - task: UseDotNet@2
        displayName: Use .NET 6
        inputs:
          version: 6.x
      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: restore
          projects: src\Services\Edu\EducationalInstitution.API\EducationalInstitution.API.csproj
      - task: DotNetCoreCLI@2
        displayName: Build Educational Institution API
        inputs:
          projects: src\Services\Edu\EducationalInstitution.API\EducationalInstitution.API.csproj
          arguments: --configuration $(BuildConfiguration)
      - task: DotNetCoreCLI@2
        displayName: Educational Institution API Unit Tests
        inputs:
          command: test
          projects: src\Services\Edu\EducationalInstitution.API.UnitTests\EducationalInstitution.API.UnitTests.csproj
          arguments: --configuration $(buildConfiguration)
          workingDirectory: src/Services/Edu/EducationalInstitution.API.UnitTests
      - task: DotNetCoreCLI@2
        displayName: Educational Institution API Integration Tests
        inputs:
          command: test
          projects: src\Services\Edu\EducationalInstitution.API.IntegrationTests\EducationalInstitution.API.IntegrationTests.csproj
          arguments: --configuration $(buildConfiguration)
          workingDirectory: src/Services/Edu/EducationalInstitution.API.IntegrationTests
      - task: DotNetCoreCLI@2
        displayName: Publish
        inputs:
          command: publish
          arguments: --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)
      - task: PublishBuildArtifacts@1
        displayName: Publish Artifact
        condition: succeededOrFailed()
        inputs:
          PathtoPublish: $(build.artifactstagingdirectory)
          ArtifactName: $(BuildParameters.ArtifactName)
          TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
