// <auto-generated />
using System;
using EducationaInstitutionAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EducationaInstitutionAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EducationaInstitutionAPI.Data.EduInstitution", b =>
                {
                    b.Property<Guid>("EduInstitutionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocationID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("ParentInstitutionEduInstitutionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EduInstitutionID");

                    b.HasIndex("ParentInstitutionEduInstitutionID");

                    b.HasIndex("LocationID", "EduInstitutionID");

                    b.ToTable("EducationalInstitutions");
                });

            modelBuilder.Entity("EducationaInstitutionAPI.Data.EduInstitutionBuilding", b =>
                {
                    b.Property<string>("BuildingID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("EducationalInstitutionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BuildingID", "EducationalInstitutionID");

                    b.HasIndex("EducationalInstitutionID");

                    b.ToTable("EducationalInstitutionsBuildings");
                });

            modelBuilder.Entity("EducationaInstitutionAPI.Data.EduInstitution", b =>
                {
                    b.HasOne("EducationaInstitutionAPI.Data.EduInstitution", "ParentInstitution")
                        .WithMany("ChildInstitutions")
                        .HasForeignKey("ParentInstitutionEduInstitutionID");

                    b.OwnsOne("EducationaInstitutionAPI.Data.Access", "EntityAccess", b1 =>
                        {
                            b1.Property<Guid>("EduInstitutionID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("DateForPermanentDeletion")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("IsDisabled")
                                .HasColumnType("bit");

                            b1.HasKey("EduInstitutionID");

                            b1.HasIndex("DateForPermanentDeletion", "IsDisabled");

                            b1.ToTable("EducationalInstitutions");

                            b1.WithOwner()
                                .HasForeignKey("EduInstitutionID");
                        });

                    b.Navigation("EntityAccess");

                    b.Navigation("ParentInstitution");
                });

            modelBuilder.Entity("EducationaInstitutionAPI.Data.EduInstitutionBuilding", b =>
                {
                    b.HasOne("EducationaInstitutionAPI.Data.EduInstitution", null)
                        .WithMany("Buildings")
                        .HasForeignKey("EducationalInstitutionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EducationaInstitutionAPI.Data.Access", "EntityAccess", b1 =>
                        {
                            b1.Property<string>("EduInstitutionBuildingBuildingID")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<Guid>("EduInstitutionBuildingEducationalInstitutionID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("DateForPermanentDeletion")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("IsDisabled")
                                .HasColumnType("bit");

                            b1.HasKey("EduInstitutionBuildingBuildingID", "EduInstitutionBuildingEducationalInstitutionID");

                            b1.HasIndex("DateForPermanentDeletion", "IsDisabled");

                            b1.ToTable("EducationalInstitutionsBuildings");

                            b1.WithOwner()
                                .HasForeignKey("EduInstitutionBuildingBuildingID", "EduInstitutionBuildingEducationalInstitutionID");
                        });

                    b.Navigation("EntityAccess");
                });

            modelBuilder.Entity("EducationaInstitutionAPI.Data.EduInstitution", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("ChildInstitutions");
                });
#pragma warning restore 612, 618
        }
    }
}
