trigger:
  branches:
    include:
      - main
  paths:
    include:
      - /src/Services/Identity
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
    - repository: self
      type: git
      ref: main
jobs:
  - job: Job_1
    displayName: Agent job 1
    pool:
      vmImage: windows-2019
    steps:
      - checkout: self
        clean: true
      - task: NuGetToolInstaller@1
        displayName: Use NuGet 6.0.0
        inputs:
          versionSpec: 6.0.0
          checkLatest: true
      - task: UseDotNet@2
        displayName: Use .NET 6
        inputs:
          version: 6.x
      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: restore
          projects: src\Services\Identity\Identity.API\Identity.API.csproj
      - task: DotNetCoreCLI@2
        displayName: Build Identity API
        inputs:
          projects: src\Services\Identity\Identity.API\Identity.API.csproj
          arguments: --configuration $(BuildConfiguration)
      - task: DotNetCoreCLI@2
        displayName: Identity API Unit Tests
        inputs:
          command: test
          projects: src\Services\Identity\Identity.API.UnitTests\Identity.API.UnitTests.csproj
          arguments: --configuration $(BuildConfiguration)
      - task: DotNetCoreCLI@2
        displayName: Publish
        inputs:
          command: publish
          publishWebProjects: True
          projects: "**/*.csproj"
          arguments: --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)
          zipAfterPublish: True
      - task: PublishBuildArtifacts@1
        displayName: Publish Artifact
        condition: succeededOrFailed()
        inputs:
          PathtoPublish: $(build.artifactstagingdirectory)
          TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
