version: "3.9"
services:
    notification-sqldb:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
    edu-distributor:
        build:
            context: .
            dockerfile: Services/Edu/EducationalInstitution.Infrastructure/Replication/Distributor/Dockerfile
        container_name: 'edu-distributor'
        hostname: 'edu-distributor'
    edu-publisher:
        build:
            context: .
            dockerfile: Services/Edu/EducationalInstitution.Infrastructure/Replication/Publisher/Dockerfile
        depends_on:
           - edu-distributor
           - edu-subscriber
        container_name: 'edu-publisher'
        hostname: 'edu-publisher'
    edu-subscriber:
        build: 
            context: .
            dockerfile: Services/Edu/EducationalInstitution.Infrastructure/Replication/Subscriber/Dockerfile
        depends_on:
            - edu-distributor
        container_name: 'edu-subscriber'
        hostname: 'edu-subscriber'
    rabbitmq:
        image: rabbitmq:3-management-alpine
    educationalinstitution-api:
        build: 
            context: .
            dockerfile: Services/Edu/EducationalInstitution.API/Dockerfile
        depends_on:
            - edu-distributor
            - edu-publisher
            - edu-subscriber
            - identity-api
            - rabbitmq
    notification-api:
        build: 
            context: .
            dockerfile: Services/Notification/Notification.API/Dockerfile
        depends_on:
            - notification-sqldb
            - rabbitmq
            - identity-api
    aggregator:
        build:
            context: .
            dockerfile: APIGateway/Aggregator/Dockerfile
        depends_on:
            - educationalinstitution-api
            - identity-api
    identity-sqldb:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
    identity-api:
        build:
            context: .
            dockerfile: Services/Identity/Identity.API/Dockerfile
        container_name: 'identity-api'
        hostname: 'identity-api'
        depends_on:
            - identity-sqldb
            - rabbitmq