version: '3.9'

services:
   educationalinstitution-api:
       environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__WritesDB=Server=edu-publisher;Database=ProjectOne.EducationalInstitutions.Writes;User Id=sa;Password=Pass@word;ConnectRetryInterval=30;
            - ConnectionStrings__ReadsDB=Server=edu-subscriber;Database=ProjectOne.EducationalInstitutions.Reads;User Id=sa;Password=Pass@word;ConnectRetryInterval=30;
            - ConnectionStrings__IntegrationTestsDB=Server=edu-publisher;Database=ProjectOne.EducationalInstitutions.Tests;User Id=sa;Password=Pass@word;ConnectRetryInterval=30;
            - EventBus__HostName=rabbitmq
       ports:
            - "50001:50001"
            - "53001:53001"
   notification-api:
       environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://0.0.0.0:80
            - ConnectionStrings__ConnectionToNotificationDB=Server=notification-sqldb;Database=ProjectOne.Notifications;User Id=sa;Password=Pass@word;ConnectRetryInterval=30;
            - EventBus__HostName=rabbitmq
       ports:
            - "16780:80"
   aggregator:
       environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://0.0.0.0:80
            - ServicesUrls__gRPCEdu=http://educationalinstitution-api:50001
       ports:
            - "61632:80"
   edu-distributor:
       environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Pass@word
            - MSSQL_AGENT_ENABLED=true
       ports:
            - "1451:1433"
   edu-publisher:
       environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Pass@word
            - MSSQL_AGENT_ENABLED=true
       ports:
            - "1452:1433"
   edu-subscriber:
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Pass@word
            - MSSQL_AGENT_ENABLED=true
        ports:
            - "1453:1433"
   notification-sqldb:
       environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Pass@word
            - MSSQL_AGENT_ENABLED=true
   rabbitmq:
       ports:
            - "15672:15672"
            - "5672:5672"